extends: "@istanbuljs/nyc-config-typescript"

reporter:
  - html
  - lcovonly
  - clover
  # those 2 are for commandline outputs
  - text
  - text-summary
report-dir: docs/reports/coverage

# Coverage gates
check-coverage: true
functions: 100
lines: 100
statements: 100
branches: 100